-- liquibase formatted sql
-- changeset nikolai:create-all-tables

--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3
-- Dumped by pg_dump version 13.3

-- Started on 2022-12-20 12:56:30 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 72259)
-- Name: not_found; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS public.not_found (
                                  id integer NOT NULL,
                                  not_found_query character varying(255)
);


ALTER TABLE public.not_found OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 72257)
-- Name: not_found_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.not_found ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.not_found_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 201 (class 1259 OID 59582)
-- Name: slang_translator; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS public.slang_translator (
                                         id integer NOT NULL,
                                         description text NOT NULL,
                                         search_query_ru character varying(255),
                                         search_query_en character varying(255)
);


ALTER TABLE public.slang_translator OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 59580)
-- Name: slang_translator_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.slang_translator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.slang_translator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 3259 (class 0 OID 72259)
-- Dependencies: 203
-- Data for Name: not_found; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3257 (class 0 OID 59582)
-- Dependencies: 201
-- Data for Name: slang_translator; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (1, 'Информационные технологии', 'айти', 'it');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (2, 'Анлим (или «безлимит», от англ. «unlimited») — в широком смысле - неограниченный доступ к чему-либо', 'анлим', 'unlimited');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (3, 'Апгрейд (от англ. «upgrade») — усовершенствование / обновление и модернизация компьютерной техники (железа), программного обеспечения, аппаратуры и т.д.', 'апгрейд', 'upgrade');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (4, 'Апдейт (от англ. «update») — обновление/модернизация программного обеспечения (софта)', 'апдейт', 'update');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (5, 'Апи (или «Апишка», от англ. «API», «Application Programming Interface») — программный интерфейс приложения или интерфейс прикладного программирования. Простыми словами, это описание вариантов взаимодействия компьютерных программ между собой', 'апи', 'api');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (6, 'Апрув (или «аппрув», «заапрувить», от англ. «approve») — подтверждение, согласие, одобрение чего-либо после проведения предварительной проверки/модерации', 'апрув', 'approve');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (7, 'Аттач (от англ. «attach») — файл, который прикреплён к электронному письму или XML', 'аттач', 'attach');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (8, 'Аутсорс (или «аутсорсинг», от англ. «outsource») — распространенная практика, когда компания передает часть рабочих задач специалистам вне своего штата (фрилансерам / работникам других компаний)', 'аутсорс', 'outsource');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (9, 'Баг (или «программная ошибка», от англ. «bug») — некая ошибка/дефект в написанном коде/программе, из-за которой программа ведет себя неожиданно, и, как следствие, выдает неправильные результаты', 'баг', 'bug');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (10, 'Бенч (от англ. «bench») — обычно, имеется ввиду режим ожидания, простой специалиста в связи с отсутствием новых задач/проектов (при этом он получает зарплату)', 'бенч', 'bench');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (11, 'Бигдата (от англ. «big data») — набор специализированных методов и инструментов, использующихся для хранения и обработки огромных объемов данных, т.е. таких, которые характеризуются «тремя V»: volume (объём), velocity (скорость прироста и обработки), variety (многообразие)', 'бигдата', 'big data');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (13, 'Блокчейн (от англ. «blockchain») — методика построения непрерывной последовательной цепочки блоков (связного списка), которые содержат определенную информацию. Внесение изменений в информацию существующих блоков очень проблематично, т.к., чаще всего, копии цепочек блоков хранятся на множестве разных компьютеров независимо друг от друга. Кроме того, если необходимо внести какие-либо изменения в информацию одного из блоков, придётся редактировать и все последующие блоки', 'блокчейн', 'blockchain');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (14, 'Бот (от англ. «robot») — ПО, предназначенное для автоматизации рутинных задач человека, иногда с зачатками искусственного интеллекта (к примеру, чат- бот на сайтах, который отвечает на заранее запрограммированные несложные вопросы)', 'бот', 'bot');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (15, 'Брейншторм (от англ. «brainstorm») — мозговой штурм, используется компаниями для генерации интересных идей и вариантов, а так же для поиска решений существующих проблем', 'брейншторм', 'brainstorm');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (16, 'Бэкап (от англ. «backup») — резервное копирование, т.е. создание резервной копии информации/проекта/сайта, для того, чтобы при каких-либо ошибках и сбоях иметь возможность восстановить данные. Безопасным считается регулярное обновление бэкапов и хранение их на различных устройствах', ' бэкап', 'backup');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (17, 'Бэкенд (от англ. «back-end») — непосредственно сама программно-аппаратная или серверная часть приложения, а также разработка этой «внутренней части» сайтов/ПО/приложений', 'бэкенд', 'back-end');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (18, 'Бэклог (от англ. «backlog») — перечень задач по функционалу в порядке приоритета для реализации в следующих версиях продукта', 'бэклог', 'backlog');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (19, 'Валидация (от англ. «validation») — это проверка систем, процессов, пользователей насколько они соответствует определенным заданным условиям', 'валидация', 'validation');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (20, 'Варнинг (или «ворнинг», от англ. «warning») — предупреждающее сообщение в интерфейсе. Не является ошибкой, но может иметь негативные последствия для написанного кода', 'варнинг', 'warning');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (21, 'Вебинар (от англ. «web based seminar») — это выступление, лекция или презентация на выбранную тему, проходящая в сети Интернет в онлайн режиме. Также, вебинаром называют и запись проведенного ранее онлайн вебинара', 'вебинар', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (22, 'Винда (или «виндоза», «виндоуз», «виндовоз», от англ. «windows») — операционная система Windows, впервые созданная корпорацией Microsoft в 1985 году. Простыми словами, это главная программа, которая начинает работать после включения ПК и позволяет юзеру работать с файлами, использовать Интернет и запускать различные программы', 'винда виндоза виндовоз', 'windows');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (23, 'Винт (или «веник», «винчестер», «жёсткий диск») — накопитель на жёстких магнитных дисках - одно из самых важных составных частей любого ПК. Это запоминающее устройство для хранения/накопления данных на компьютере', 'винт веник винчестер', 'hdd');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (24, 'Витуха (или «витя», «витюха», «витая пара») — определенный вид кабеля связи (витая пара), представляющий собой изолированные пары скрученных между собой проводников в пластиковой оболочке', 'витуха витая пара', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (25, 'Воркшоп (от англ. «workshop») — мероприятие обучающего характера для специалистов из определённой сферы деятельности (программистов, фотографов, дизайнеров и т.д.). Обучение проводит обычно один из ведущих работников компании, вместе с которым участники совместно выполняют определенное задание/решают проблему', 'воркшоп', 'workshop');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (26, 'Выделенка — выделенная линия, т.е. подключение к интернет-провайдеру с использованием индивидуальной линии (кабеля) и сетевой карты', 'выделенка', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (27, 'Выкатить — вывести приложение/программу/сайт в открытый доступ для всех пользователей', 'выкатить', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (28, 'Выпадашка — элемент интерфейса ПО/приложения/сайта, сделанный по типу «выпадающего списка» («droplist»). Используется в тех случаях, когда необходимо что-то конкретизировать/детализировать, не перегружая при этом большим количеством информации главный экран', 'выпадашка', 'droplist');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (29, 'Гайд (от англ. «guide») — прописанная инструкция, руководство по достижению определенной цели, правила и порядок действий при выполнении поставленной задачи', 'гайд', 'guide');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (30, 'Гектар (или «гиг») — другое название гигабайта (кратен единице байта) - единица измерения количественной информации, равная 109 (1 000 000 000) или 230 (1 073 741 824) байт', 'гектар гиг', 'gbyte');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (12, 'некорректный / нерабочий / содержащий ошибку. Так, «битая ссылка» ведет на несуществующую страницу с ошибкой 404 (Error 404), «битые пиксели» - неправильно отображают цвета на мониторе', 'битый', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (31, 'Генерить (или «сгенерить», от англ. «generate») — сгенерировать, создать что-то новое, сформировать что-либо. Часто применяется по отношению к новым идеям и вариантам', 'генерить', 'generate');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (32, 'Гестуры (от англ. «gestures») — определенные движения по экрану пальца или стилуса, которые позволяют заменить те или иные команды или их последовательности. Это существенно ускоряет и упрощает работу на мобильных устройствах', 'гестуры', 'gestures');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (33, 'Гит — 1) система контроля и управления версиями Git, консольная утилита для отслеживания и ведения истории изменения файлов в проекте; 2) веб-сервис GitHub для хостинга IT-проектов и совместной работы над ними', 'гит', 'git');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (34, 'Гитхаб (от англ. «GitHub») — крупный веб-сервис для хранения (хостинга) репозиториев IT-проектов и совместной работы над ними. GitHub является своеобразной соц. сетью для программистов, которая позволяет им ознакомится с кодом друг друга, прокомментировать его и помочь в разработке', 'гитхаб', 'github');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (35, 'Грызун — компьютерная мышь, специальное устройство для управления курсором и передачи определенных команд ПК', 'грызун', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (36, 'Гуй (или «GUI», от англ. «Graphical User Interface») — графический интерфейс пользователя, состоящее из окон, разнообразных меню, кнопок и прочих виджетов', 'гуй', 'gui');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (37, 'Дамп  (от англ. «dump») — файл, содержащий резервную копию системы/памяти компьютера/базы данных, актуальную на момент его создания. В разработке дампы применяют для создания и поддержания в актуальном состоянии системы бэкапа', 'дамп', 'dump');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (38, 'Дата центр (или «ЦОД», от англ. «data center») — это специализированное здание для размещения и обслуживания серверного, сетевого оборудования
', 'дата центр цод', 'data center');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (39, 'Даунлоад (от англ. «download») — процесс передачи (скачивания) файловых данных из одного устройства в другое
', 'даунлоад', 'download');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (40, 'Движок (или «двигло») — прикладная часть программного кода (программа/часть программы/комплекс программ/библиотека), выделенная для реализации определенной задачи', 'движок двигло', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (41, 'Дебажить  (от англ. «debug», «debugging») — производить поиск ошибок/багов в программе с последующим их исправлением', 'дебажить', 'debug debugging');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (42, 'Девайс (или «девица», «дежице», от англ. «device») — любое полезное техническое устройство/приспособление, конструктивно законченная техническая система, имеющая определённое функциональное назначение (ноутбук/смартфон/планшет/умные часы и т.д.).
', 'девайс девица', 'device');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (43, 'Девелопер (или «разработчик», от англ. «developer») — специалист, который непосредственно занимается разработкой ПО и приложений', 'девелопер разработчик', 'developer');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (44, 'Девелопмент  (от англ. «development») — разработка чего-либо: сайтов, программного обеспечения, приложений, игр и т.д.
', 'девелопмент', 'development');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (45, 'Дедлайн  (от англ. «deadline») — крайний итоговый срок, к которому должна быть выполнена та или иная задача/сдан проект/достигнута цель', 'дедлайн', 'deadline');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (46, 'Деплой  (или «задеплоить», от англ. «deploy») — развёртывание (перенос/помещение) программного обеспечения (исполняемого кода) на выбранный сервер или конкретное устройство, где оно будет работать', 'деплой задеплоить', 'deploy');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (47, 'Дефолтный  (или «по дефолту», от англ. «default») — значения, которые присваиваются параметрам автоматически («по умолчанию») в тех случаях, когда юзер не задал им ни одно из допустимых значений', 'дефолтный', 'default');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (48, 'Джуниор (или «джун», «июнь», от англ. «Junior Developer») — общепринятое в it название младшего разработчика (начальный уровень программиста), специалиста без опыта или с минимальным опытом работы', 'джуниор джун июнь', 'junior');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (49, 'Дидос (или «дидосить», «задидось», «ДДоС», от англ. «Distributed Denial of Service») — массированная атака на сетевые ресурсы или каналы связи с помощью заражённых «третьих» компьютеров-зомби с целью сделать их недоступными для легитимных пользователей. DDoS-атаки заключаются в единовременной отправке ресурсу огромного количества запросов с одного или многих компьютеров, расположенных в сети Интернет', 'дидос дидосить', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (50, 'Дисконнект (или «отконнектиться», «расконнектиться», от англ. «disconnect») — временное отключение/разрыв/потеря связи или соединения', 'дисконнект', 'disconnect');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (51, 'Домен  (или «доменное имя», «доменный адрес», от англ. «domain») — 1) уникальный онлайн адрес/имя сайта, место его размещения в Интернете. Например, science.involta.ru — это домен второго уровня, который состоит из доменного имени science.involta и домена первого уровня .ru; 2) часть фидонетовского адреса, которая содержит название глобальной сети (@fidonet.org)', 'домен', 'domain');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (52, 'Драйвер (или «драйверА», «дрАйверы», «дрова», от англ. «driver») — компьютерное ПО, с помощью которого другое ПО/ОС взаимодействует с аппаратным обеспечением, подключаемого устройства (наушники, принтер, колонки, видеокарта и т.д.)', 'драйвер дрова', 'driver');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (53, 'Дроплист (или «выпадашка», «дропдаун», от англ. «drop list») — элемент графического интерфейса пользователя (выпадающий / раскрывающийся список), дающий возможность юзеру выбрать одно из нескольких существующих значений параметра
', 'дроплист выпадашка', 'drop list');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (54, 'Дропнуть (от англ. «drop») — в IT подразумевается обычно удаление чего-либо (базу данных, приложение, таблицу и т.д.)', 'дропнуть', 'drop');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (55, 'Железо — материально-техническая часть/комплектующие компьютеров/ноутбуков/смартфонов и т.д.', 'железо', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (56, 'Залить — загрузить файлы на сервер/сайт или закачать информацию в базу данный/файлообменник', 'залить', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (57, 'Запилить — создать/сделать/выложить что-либо, добавить какую-то функциональность', 'запилить', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (58, 'Заплатка (или «патч») — дополнение или обновление, призванное исправить существующие ошибки/баги/глюки в системе или ПО. Процесс применения патча (заплатки) к программе называется пропатчиванием', 'заплатка патч', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (59, 'Засерить — сделать выбранный элемент разрабатываемого интерфейса неактивным (обычно обозначается серым цветом)
', 'засерить', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (60, 'Зафакапить  (от англ. «fuck up») — полностью провалить поставленную задачу, целиком испортить задание', 'зафакапить', 'fuck up');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (61, 'Имхо  (от англ. «IMHO», «In My Humble Opinion») — по моему скромному мнению. В русифицированной версии расшифровывается как: «Имею Мнение Хрен Оспоришь»', 'имхо', 'imho');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (62, 'Инкапсуляция (от англ. «encapsulation») — 1) упаковка данных и/или функций в единый компонент; 2) процесс скрытого хранения деталей реализации объекта от пользователей/программистов) и предоставление им для работы интерфейсов классов', 'инкапсуляция', 'encapsulation');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (63, 'Камень (или «проц», «кристалл», «ЦП») — центральный процессор, основная составная часть каждого компьютера, выполняет в системе роль своеобразной мини атс
', 'камень проц', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (64, 'Капча (от англ. «CAPTCHA») — картинка, предназначенная для проверки пользователя на предмет его реальности (не является ли он ботом). Капча используется с целью защиты от авто-регистраций и спам-ботов
', 'капча', 'captcha');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (65, 'Качалка  (от англ. «download manager») — менеджер загрузок, программа, которая обеспечивает возможность загрузки выбранных файлов из Интернета или локальной сети', 'качалка', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (66, 'Кейс  (от англ. «case») — реальная ситуация/случай из практики, произошедшие с человеком. Сейчас обычно используется применительно к опыту и конкретным наработкам специалиста, подтвержденным цифрами и наглядными примерами', 'кейс', 'case');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (67, 'Кило (или «кил») — килобайт, единица измерения количества информации, равная 1024 байтам (иногда 1000 байтам)', 'кило', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (68, 'Клава (или «рояль») — клавиатура: устройство с комплектом клавиш, предназначенное для ввода/вывода данных и управления гаджетом, к которому оно подключено', 'клава рояль', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (69, 'Кладж (или «клудж», от англ. «kludge») — управляющие строки, которые содержат техническую информацию о письме, скрытую по умолчанию при просмотре в редакторе', 'кладж клудж', 'kludge');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (70, 'Коворкинг (от англ. «coworking») — современное арендованное помещение открытого типа, предназначенное для удобной и комфортной работы специалистов различных сфер деятельности, фрилансеров', 'коворкинг', 'coworking');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (71, 'Коммит (от англ. «git commit») — запись индексированных изменений в хранилище (репозиторий), содержащая данные об изменениях, комментарий и имя автора', 'коммит', 'commit');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (72, 'Коммитить  (или «закоммитить», «сделать коммит», от англ. «commit») — проводить сохранение/фиксацию произведенных изменений кода в хранилище кода (репозиторий)', 'коммитить', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (73, 'Компилить (от англ. «compilating») — осуществлять компиляцию, т.е. перевод написанного кода с языка программирования на машинный язык', 'компилить', 'compilating');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (74, 'Комьюнити  (от англ. «community») — 1) ограниченное сообщество/группа людей, которые являются пользователями одного и того же сетевого ресурса/сообщества/приложения; 2) группа разработчиков и других специалистов, работающих над одним проектом или несколькими продуктами одной компании', 'комьюнити', 'community');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (75, 'Контент (от англ. «content») — содержательное наполнение сайта/соц.сети/блога (текстовки, изображения, аудио и видео файлы), поддающееся простому редактированию через админ-панель', 'контент', 'content');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (76, 'Конфа (от англ. «conference») — 1) сокращенное название конференции: общение между группой людей (реальное собрание или удаленное по средствам интернет - соединения); 2) конфигурационный файл ПО, позволяющий изменять его настройки', 'конфа', 'conference');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (77, 'Конфиг — текстовый конфигурационный файл, который используется для хранения директивы настроек системы/команды загрузки драйверов', 'конфиг', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (78, 'Копипаст (от англ. «copy/paste») — команды "скопировать" и "вставить". Иногда так иронично называют псевдо-творческую деятельность, сводящуюся лишь к копированию уже существующей информации (человек-копипастер)', 'копипаст', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (79, 'Корень — 1) корневая директория на диске: папка/каталог, являющаяся вышестоящей одновременно для всех существующих файлов и подпапок на устройстве; 2) root - аккаунт сисадмина в UNIX-подобных системах с полными правами', 'корень', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (80, 'Костыль  — наскоро реализованное решение проблемы в готовом коде. Является временной мерой, поддерживающей работоспособность программы, пока программисты трудятся над качественным глобальным решением', 'костыль', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (81, 'Кракер  (или «крэкер», «крякер») — опытный программист, который пишет кряки для взлома программной системы защиты (иногда их ошибочно путают с хакерами)', 'кракер', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (82, 'Кряк (или «крэк», «кряка», «крякалка», ««таблэтка»», «лекарство», от англ. «crack») — специальная программа или дополнение для взлома платного ПО, делающее возможным его бесплатное использование', 'кряк', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (83, 'Крякнуть  (или «крэкнуть», от англ. «crack») — взломать платное ПО с целью его дальнейшего бесплатного использования', 'крякнуть', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (84, 'Куки (или «кука», «кукисы», «печенька», от англ. «cookies») — небольшой файл текстового формата, который сайт посылает на диск пользователя для его идентификации и сохранения настроек', 'куки', 'cookies');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (85, 'Лаг (или «лаги», «лагать», от англ. «lag») — торможение или медленная работа какой-либо системы, к примеру, программы или компьютерной игры. Возникает по причине недостаточных характеристик устройства, либо из-за низкой скорости интернета (если речь о передаче данных по сети)', 'лаг', 'lag');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (86, 'Легаси-код (от англ. «legacy code») — изживший себя код, который был написан кем-то очень давно и с которым программистам теперь приходится работать', 'легаси', 'legasy');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (87, 'Либа  (от англ. «Library») — в программировании имеется ввиду библиотека кода или DLL в Windows', 'либа', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (88, 'Линк  (или «ссылка», «связь», «гиперссылка», от англ. «link») — 1) гипертекстовая ссылка на какой-либо сайт/ресурс/документ/урл (URL)', 'линк', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (89, 'Линукс  (от англ. «Linux») — бесплатная, полностью готовая ОС на основе ядра Linux. Исходные коды Linux доступны для изменений и просмотров любым юзером', 'линукс', 'linux');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (90, 'Лиса (или «лисичка») — свободный браузер Mozilla Firefox с открытым исходным кодом, основанный в 2003 году', 'лиса', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (91, 'Лист (от англ. «List») — изменяемый список, структура данных для хранения объектов различных типов, построенная на двусвязных списках', 'лист', 'list');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (92, 'Личка (или «ЛС», «л/с», «приватный чат») — личные сообщения: форма общения в Интернет-пространстве между двумя людьми, суть которой заключается в приватности диалога', 'личка', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (93, 'Логиниться  (или «залогиниться», от англ. «login») — процесс входа в систему (авторизация в ПО, на сайте) под ранее зарегистрированной учетной записью путём ввода логина и пароля', 'логиниться', 'login');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (94, 'Лого (от англ. «logo») — логотип: уникальный графический элемент (эмблема), используемый компаниями/брендами для идентификации себя на рынке', 'лого', 'logo');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (95, 'Лог-файл  (или «лог», от англ. «log file») — текстовый файл (файл или таблица в базе данных) для внесения в последовательном порядке всех совершенных действия в ПО/сервере, к примеру: шаги юзеров, время произошедших ошибок и сбоев и тд.', 'логи', 'log');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (96, 'Майнинг  (от англ. «mining») — сейчас ассоциируется, в основном, с добычей криптовалюты с помощью мощных компьютеров, выполняющих сложные математические операции', 'майнинг', 'mining');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (97, 'Макрос (или «макрокоманда», «макроопределение», от англ. «makros») — 1) программный алгоритм действий, написанный пользователем (обычно применяются для выполнения рутинных действий); 2) символьное имя в шаблонах, заменяемое при обработке препроцессором на последовательность символов', 'макрос', 'makros');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (98, 'Мануал  (от англ. «manual») — краткое руководство пользователя, инструкция по использованию чего-то: ПО, оборудования, сервиса и т.д.', 'мануал', 'manual');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (99, 'Мейнстрим (от англ. «mainstream») — направление/течение, которое в определенное время является популярным и преобладает в какой-либо сфере общественной жизни: научной, культурной, технической и т.д.', 'мейнстрим', 'mainstream');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (100, 'Ментор (от англ. «mentor») — наставник/учитель, опытный руководитель, который является носителем ценных знаний и умений', 'ментор', 'mentor');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (101, 'Меншить  (от англ. «mention») — упоминание имени другого пользователя в чатах/группах/соц. сетях c целью привлечь его внимание к диалогу или же предоставить прямую ссылку на него для удобства поиска другими участниками беседы', 'меншить', 'mention');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (102, 'Метр (или «мег», «МБ») — вариант названия единицы измерения информации, равной 1 мегабайту', 'метр мег', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (103, 'Мёржить (от англ. «Merge») — производить объединение/слияние нескольких веток кода или данных таблиц', 'мёржить', 'merge');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (104, 'Мидл (от англ. «Middle Developer») — средний уровень навыков/знаний программиста в общепринятой системе измерения (джуниор/мидл/сеньор)', 'мидл', 'middle');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (105, 'Митап (от англ. «meetup») — сходка/встреча специалистов из одной или близких сфер работы для взаимного обмена накопленным опытом, а иногда просто для неформального общения', 'митап', 'meetup');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (152, 'Пул реквест (от англ. «pull request») — запрос на подтверждение коммита, т.е. на изменение кода в чужом репозитории', 'пул реквест', 'pull request');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (106, 'Митинг  (от англ. «meeting») — в it-сфере термин употребляется применительно к собраниям/встречам, на которых обсуждаются итоги в проведенной работы, выявляются сложности и недоработки, ставятся новые цели и задачи', 'митинг', 'meeting');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (107, 'Мулька — 1) полезная фича, какая-то "изюминка" в ПО/приложении, скрытая доп. функция; 2) этикетка, ярлычок, фирменный лого (обычно на одежде)', 'мулька', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (108, 'Мыло (или «емейл», «мейл», «имейл», от англ. «e-mail») — индивидуальный адрес электронной почты пользователя', 'мыло', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (109, 'Накатить — внести изменения, развернуть, опубликовать новую рабочую версию приложения. Противоположное термину «откатить»', 'накатить', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (110, 'Нуб  (или «нубчик», «нубас», «нубарь», «нубак», от англ. «newbie») — неопытный новичок, человек, имеющий проблемы с пониманием или применением чего-то', 'нуб', 'newbie');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (111, 'ООП (или «Объектно-Ориентированное Программирование») — методология/подход в программировании, в рамках которого программы представляются в виде совокупности объектов, являющихся экземплярами определенных классов, а те, в свою очередь, образуют иерархию наследования', 'ооп', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (112, 'Опенсорс  (или «открытый код», от англ. «open source software») — ПО/софт (обычно, некоммерческие) с исходным кодом открытого типа, который может использовать/дополнять/редактировать любой желающий', 'опенсорс', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (113, 'Опенспейс (от англ. «open space») — рабочее пространство открытого типа без стен и перегородок, в котором специалисты работают все вместе', 'опенспейс', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (114, 'ОС  (или «ось», «операционка», от англ. «Operating System») — операционная система, комплекс связанных межд собой ПО, позволяющий управлять аппаратной частью и ресурсами ПК/ноутбуков/смартфонов и т.д.', 'ос ось', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (115, 'Откатить (от англ. «rollback») — убрать внесенные ранее изменения, вновь вернув предыдущую версию программы/приложения', 'откатить', 'rollback');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (116, 'Отревьюить (от англ. «review») — просмотреть на предмет ошибок, прокомментировать, дать рецензию и рекомендации', 'отревьюить', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (117, 'Офтопик (или «офтоп», «офф», от англ. «off topic») — сообщение, отличающееся по своей тематике от главной темы конференции/форума/разговора', 'офтопик', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (118, 'Оффер (или «офер», «джоб оффер», от англ. «offer») — 1) в широком смысле - любое предложение; 2) предложение о работе/вакансия с указанием должности, обязанностей и зарплаты', 'оффер офер', 'offer');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (119, 'Пага  (или «хомяк», от англ. «home page») — домашняя страница, WEB-страничка пользователя, его персональный сайт', 'пага', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (120, 'Падаван — ироничное шутливое название стажёра или джуниора в IT-сфере
', 'падаван', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (121, 'Парсер (от англ. «parser») — 1) участок кода, который ответственен за разбор; 2) круг подпрограмм, которые могут сканировать сайт, собирать и обрабатывать информацию, при этом выдавая себя за обычного посетителя; 3) объектно-ориентированный скриптовый язык программирования, предназначенный для создания HTML-страниц на веб-сервере с поддержкой CGI', 'парсер', 'parser');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (122, 'Парсить  (от англ. «parsing») — сбор и анализ информации из открытых источников, разбор чего либо', 'парсить', 'parsing');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (123, 'Паттерн (от англ. «pattern») — 1) наиболее эффективный способ решения характерных задач проектирования, в т.ч. проектирования ПО; 2) в графическом дизайне: бесшовный узор с неоднократно повторяющимися элементами', 'паттерн', 'pattern');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (124, 'Патч (или «заплатка», «пач», от англ. «patch») — дополнение или обновление it-продукта (ПО/приложения), исправляющее обнаруженные ошибки/баги/глюки (процесс применения патча - пропатчивание, пропатчить)', 'патч', 'patch');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (125, 'Пень — центральный процессор торговой марки Pentium, выпускаемый компанией Intel', 'пень', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (126, 'Песочница (от англ. «sandbox») — 1) специальная область/место/среда, где программа может безопасно выполнятся; 2) на сайте одноименный раздел выделяет категорию для записей новичков (некий фильтр)', 'песочница', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (127, 'Петля (или «луп») — фрагмент аудио или видео записи, который замыкается в кольцо (петлю) для цикличного воспроизведения', 'петля луп', 'loop');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (128, 'Пет-проект  (или «pet-проект», от англ. «pet-project») — проект (чаще всего личный), который создается и развивается исключительно для получения опыта или как хобби (изредка перерастает в полноценный проект или даже компанию)', 'пет-проект ', 'pet-project');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (129, 'Пилот (от англ. «pilot») — 1) тестовая (пилотная) версия продукта, либо отдел фирмы, выбранный для опробации/обкатывания этого продукта; 2) сетевой фильтр для сохранения техники от поломок, связанных со скачками напряжения', 'пилот', 'pilot');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (130, 'Пинг (от англ. «ping») — программа для проверки связи в сети, ее целостности и качества; 2) характеристика скорости сетевого соединения, т.е. время прохождения пакета данных до адресата и обратно (измеряется в миллисекундах)', 'пинг', 'ping');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (131, 'Пинговать (от англ. «ping») — проводить проверку ресурса на доступность с использованием утилиты «Ping»', 'пинговать', 'ping');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (132, 'Писюк (от англ. «PC», «personal computer») — персональный компьютер', 'писюк', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (133, 'Питон (или «пайтон», «путон», от англ. «Python») — популярный высокоуровневый язык программирования общего назначения, отличающийся хорошей читабельностью кода и чистым выразительным синтаксисом', 'питон пайтон', 'python');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (134, 'Планка (или «плашка») — отдельный модуль оперативной памяти, содержащий микросхемы запоминающего устройства
', 'планка', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (135, 'ПО (или «ПэО», от англ. «software») — программное обеспечение: одна или несколько программ (комплекс), которые используются для нормального функционирования компьютера', 'по', 'software');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (136, 'Подвал (или «футер») — в веб-дизайне так называют нижнюю часть страницы/сайта, содержащую служебную информацию', 'подвал футер', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (137, 'Подкаст (от англ. «podcast») — цикл уроков видео или аудио формата, рассказы/лекции по определённой тематике, чаще всего образовательного характера', 'подкаст', 'podcast');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (138, 'Попап (от англ. «pop-up») — всплывающее окно на сайте/в приложении, обычно рекламного характера', 'попап', 'pop-up');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (139, 'Пост (от англ. «post») — опубликованная запись/публикация/статья в интернет-пространстве (соц.сети, форуме, блоге)', 'пост', 'post');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (140, 'Постить (от англ. «post») — 1) делать и публиковать посты в соцсетях, в блоге, на форуме', 'постить', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (141, 'Пофиксить (или «фиксить», от англ. «fix») — исправить/наладить работу, внести необходимые правки', 'пофиксить', 'fix');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (142, 'Поюзать (или «юзнуть», от англ. «use») — попробовать в использовании что-то (например, новый гаджет), протестировать неизвестный ранее функционал', 'поюзать', 'use');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (143, 'Превьюшка (или «превью», от англ. «Preview») — компактные/уменьшенные в несколько раз изображения (миниатюры) для более удобного предварительного просмотра', 'превьюшка', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (144, 'Провалиться (от англ. «drill down») — 1) раскрыть выпадающее меню приложения/сайта для просмотра детализированных данных; 2) перейти по клику из общей формы к необходимому файлу/документу', 'провалиться', 'drill down');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (145, 'Прога (от англ. «program») — программа/программное обеспечение/утилита', 'прога', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (146, 'Прогать (или «прожить», от англ. «programming») — заниматься программированием, писать код программы/приложения
', 'прогать', 'programming');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (147, 'Программер (или «прог», «прогер», от англ. «programmer») — программист, человек, занимающийся программированием/разработкой ПО', 'программер прогер', 'programmer');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (148, 'Прод (или «продакшн», «продуктив», от англ. «production», «production environment») —  1) код для рабочей версии ПО/приложения; 2) в широком смысле:процесс создания какого-либо проекта или продукта (обычно, творческого) ; 3) компьютер/сервер, где запускается готовое работоспособное приложение; 4) реальная среда работы сайта, т.е. сам сайт, установленный на сервер и доступный для посетителей; 5) продуктивная эксплуатация программного продукта', 'прод продакшн', 'production');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (149, 'Прокси-сервер (или «прокси», «прокся», от англ. «proxy») — некое ПО/сервер, являющийся промежуточным звеном (посредником) между юзером и конечным сайтом/сервером. Прокси-сервер позволяет одним компьютерам выполнять запросы к другим от своего имени, чтобы обеспечить приватность, конфиденциальность и затруднить возможность отслеживания пользователя', 'прокси-сервер', 'proxy');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (150, 'Профит  (от англ. «profit») — 1) в широком смысле - определенный положительный результат чего-либо: прибыль/выгода/польза; 2) на бирже: разницу между вложенными инвестициями и полученным чистым доходом', 'профит', 'profit');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (151, 'Прошивка — ПО/программный код, встроенный в энергонезависимую память устройства и управляющий его работой (модем, GPS-навигатор, смартфон, маршрутизатор и др.)', 'прошивка', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (153, 'Пушить (или «запушить», от англ. «push») — 1) использовать команду push, публиковать что-то, например, выгружаемые локальные изменения, код на git; 2) настаивать, принуждать к чему-либо, заставлять, давить', 'пушить запушить', 'push');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (154, 'Пэхапэ  (или «пыха», от англ. «PHP») — язык программирования PHP: опенсорcный скриптовый язык, активно применяемый при разработке серверных частей современных веб-проектов', 'пэхапэ пыха', 'php');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (155, 'Радиобаттон (от англ. «radio button») — элемент интерфейса, позволяющий пользователю выбрать только одну опцию (пункт) из предопределенного набора (группы). Обычно выглядит как пустой кружочек или ромбик. При выборе «зажигается»', 'радиобаттон', 'radio button');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (156, 'Разраб  (от англ. «developer») — сокращение от разработчик, с намеком на тяжелый и подневольный «рабский» труд', 'разраб', 'developer');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (157, 'Рандом  (или «рандомный», от англ. «random») — случайная вероятность получения определенного результата при совершение какого-либо действия', 'рандом', 'random');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (158, 'Расшарить (или «шарить», «шерить», от англ. «share») — сделать открытым/поделиться доступом к какому-то ресурсу/файлу/папке в локальной сети с одним или несколькими людьми', 'расшарить', 'share');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (159, 'Ребутнуть (или «ребутить», «сделать ребут», от англ. «reboot») — перезагружать электронное устройство/систему', 'ребутнуть', 'reboot');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (160, 'Ревью (или «кодревью», от англ. «review») — рецензирование/вычитка/проверка кода с целью обнаружения и исправления ошибок', 'ревью', 'review');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (161, 'Регэкспы (или «регулярки», «регулярные выражения», от англ. «regexp,regular expressions») — формальный язык поиска и осуществления манипуляций с подстроками в тексте, который основан на применении метасимволов. Поддерживается практически всеми современными языками программирования', 'регэкспы', 'regexp regular expressions');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (162, 'Редирект (от англ. «redirect») — автоматическое перенаправление/переадресация юзера куда-либо: на другой сайт, на другую страницу, на другую почту и т.д.', 'редирект', 'redirect');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (163, 'Рекурсия (от англ. «recursion») — определение/описание какого-либо объекта/процесса с помощью самого этого объекта/процесса', 'рекурсия', 'recursion');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (164, 'Релиз (от англ. «release») — представление готовой стабильной версии продукта, прошедшей тестирование (игры/программы/песни/альбома), ее выпуск в открытый доступ', 'релиз', 'release');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (165, 'Репозиторий (или «репа», от англ. «repository») — хранилище исходных файлов проекта (программ, объектов, метаданных и т. п.)', 'репозиторий репа', 'repository');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (166, 'Рефакторинг кода (от англ. «refactoring») — корректировка исходного кода ПО для того, чтобы сделать его "чистым", т.е. простым и легким для понимания и последующей поддержки', 'рефакторинг кода', 'refactoring');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (167, 'Референс (или «рефка», «реф», от англ. «reference») — пример/образец, дающий приблизительное представление о том, что хотелось бы увидеть или получить в итоге', 'референс рефка', 'reference');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (168, 'Роутинг (или «рутинг», «маршрутизация», от англ. «routing») — процесс определения маршрута следования информации/данных в сетях связи (трафика)', 'роутинг рутинг', 'routing');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (169, 'Руби (от англ. «Ruby») — интерпретируемый язык программирования высокого уровня "Ruby". Лёгкий в разработке, используется, в основном, при разработке веб-приложений', 'руби', 'ruby');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (170, 'Саппорт (или «супорт», «поддержка», «сап», от англ. «support») — служба технической поддержки, в которую пользователи продукта или услуги могут обратиться за оказанием помощи по разрешению возникших трудностей и получением дополнительной информации', 'cаппорт супорт', 'support');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (171, 'Секьюрный  (от англ. «security») — безопасный, надежный, защищенный', 'секьюрный', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (172, 'Сеньор (или «сеньор-помидор», «сеньйор,сениор», от англ. «Senior Developer») — самый высокий уровень знаний/подготовки и навыков специалиста в it-сфере', 'сеньор', 'senior');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (173, 'Сервак (или «сервер», «сервант», «сёрвер», «аппаратное обеспечение», от англ. «server») — специализированный мощный компьютер, предназначенный для выполнения сервисного ПО, хранения данных и обеспечения доступа к ним', 'сервак сервер', 'server');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (174, 'Сессия  (от англ. «session») — 1) в веб-аналитике: последовательность запросов отдельного пользователя во время посещения определенного сайта; 2) период от входа на сервер/систему/сайт до выхода из них; 3) период от запуска браузера до его закрытия', 'сессия', 'session');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (175, 'Сетевуха (или «сетевуха», «сетевая плата», «сетевая карта», «сетевой адаптер») — специальное интерфейсное устройство, которое позволяет ПК взаимодействовать с другими устройствами локальной сети', 'сетевуха', '');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (176, 'Сетка — 1) локальная сеть , т.е. среда взаимодействия нескольких ПК; 2) в сфере дизайна: модульная сетка, используемая для дизайна и вёрстки страниц', 'сетка', '');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (177, 'Сидер  — юзер, который может инициировать раздачу, т.к. обладает готовым к раздаче файлом', 'сидер', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (178, 'Скилл (или «скиллы,скилы», от англ. «skill») — навыки, умения, мастерство в определенной сфере деятельности', 'скилл', 'skill');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (179, 'Скипнуть  (от англ. «skip») — пропустить или пролистать (обычно применяется к уведомлениям или рекламе)', 'скипнуть', 'skip');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (180, 'Скопипастить (от англ. «copy-paste») — позаимствовать/скопировать откуда-либо информацию и без изменений добавить ее в свой проект', 'скопипастить', 'copy-paste');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (181, 'Скрам (от англ. «scrum») — один из методов управления проектами, является частью гибкой методологии разработки Agile. Обычно используется в сфере разработки ПО, но может применятся и в других производственных отраслях', 'скрам', 'scrum');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (182, 'Скрин (или «скриншот», от англ. «screenshot») — снимок экрана компьютера или смартфона в данный момент времени, сохраненный в графический файл', 'скрин скриншот', 'screenshot');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (183, 'Скрипт (от англ. «script») — 1) программный файл сценария (часть написанного кода), автоматизирующий какую-то задачу, предотвращая работу вручную; 2) некий сценарий, где прописан ход беседы/последовательность действий при общении с клиентом (по телефону, лично в точке продаж и т.д.)', 'скрипт', 'script');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (184, 'Скроллинг (от англ. «scrolling», «scroll») — прокрутка экрана (колесом мыши, бегунком на странице или движением пальца по сенсорному дисплею) с целью просмотра большого блока информации (например, длинная статья или книга)', 'скроллинг', 'scrolling');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (185, 'Сносить (или «снести») — удалять, деактивировать, стирать имеющиеся настройки, деинсталлировать ПО', 'сносить снести', '');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (186, 'Собес (или «собеседование», от англ. «interview») — беседа представителя работодателя с кандидатом на вакантную должность', 'собес', 'interview');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (187, 'Софт (от англ. «software») — программное обеспечение (ПО): совокупность программ, установленных на конкретном компьютере', 'софт', 'software');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (188, 'Софт скиллы (от англ. «soft skills») — навыки социализации в обществе: социальные/коммуникативные/личностные качества человека, необходимые, в том числе, для адаптации в коллективе', 'софт скиллы ', 'soft skills');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (189, 'Сплит (от англ. «split») — 1) разделение очень длинной строки на отдельные части; 2) утрата синхронизации между разными серверами в единой сети', 'сплит', 'split');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (190, 'Спрайт  (от англ. «sprite») — в компьютерной графике: графический объект, растровое изображение, отображающееся на экране', 'спрайт', 'sprite');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (191, 'Спринт  (от англ. «sprint») — в методологии управления проектами Scrum: обозначенный временной отрезок (обычно от 1 до 4 недель), за который специалисты обязаны успеть выполнить поставленную задачу', 'спринт', 'sprint');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (192, 'Стек (от англ. «Stack») — 1) в широком смысле: абстрактный тип данных; 2) список технологий, применяемых разработчиком или компанией', 'стек', 'stack');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (193, 'Стрим (от англ. «stream») — онлайн-трансляция происходящих в данный момент событий/действий', 'стрим', 'stream');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (194, 'Таска (от англ. «task») — какое-либо задание/поручение', 'таска', 'task');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (195, 'Тап  (от англ. «tap») — короткое быстрое нажатие на элемент интерфейса дисплея телефона или планшета, по аналогии с щелчком мышью н компьютере. Соответственно, даблтап – двойное нажатие', 'тап', 'tap');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (196, 'Темплейт (от англ. «template») — шаблон/заготовка, своего рода каркас для документа или письма', 'темплейт', 'template');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (197, 'Тимлид (от англ. «team leader») — главный разработчик, человек, имеющий в подчинении свою команду разработчиков', 'тимлид', 'team leader');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (198, 'Тонна — терабайт, единица измерения количества цифровой информации', 'тонна', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (199, 'Трабл (или «трабла», «грабли», от англ. «trouble») — беда, проблемы, хлопоты, неприятности', 'трабл', 'trouble');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (200, 'Тролль — человек, намеренно провоцирующий ссоры и скандалы в различных коммуникационных сетях (чатах, форумах и т.д.)', 'тролль', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (223, 'Хард скиллы (от англ. «hard skills») — лубокие/значительные технические знания, умения и опыт', 'хард скиллы', 'hard skills');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (201, 'Троян — разновидность вредоносной программы, проникающая в компьютер под видом легитимного ПО и выполняющая команды с удаленного ПК', 'троян', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (202, 'Тултип (от англ. «tooltip») — подсказка, всплывающая при наведении курсора на какой-либо активный объект интерфейса', 'тултип', 'tooltip');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (203, 'Туториал (или «тутор», от англ. «tutorial») — свод подробных обучающих уроков на какую-либо тему', 'туториал', 'tutorial');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (204, 'Тэдэшка (или «ТД») — техническая документация: набор графических и текстовых документов проекта', 'тэдэшка тд', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (205, 'Урл (или «урла», «урээл», от англ. «URL») — унифицированный указатель ресурса, определенный шаблон записи гипертекстовых ссылок на объекты в Интернете. Простыми словами, это адрес странички в Сети', 'урл', 'url');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (206, 'Утечка памяти — процесс неконтролируемого уменьшения объёма свободной оперативной или виртуальной памяти компьютера, связанный с ошибками в работающих программах, вовремя не освободивших ненужные участки памяти', 'Утечка памяти', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (207, 'Утилита (или «утилитка», «тулза», от англ. «utility») — вспомогательное программное обеспечение, предназначенное для выполнения вспомогательных работ, настройки системного оборудования, операционных систем и прочего. Другими словами, программа, которая помогает что-то сделать', 'утилита', 'utility');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (208, 'Фаервол  (или «брандмауэр», от англ. «fire wall») — программа-антивирус, обеспечивающая обнаружение и защиту компьютера от вирусов и вредоносных ПО', 'фаервол', 'fire wall');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (209, 'Факап (или «облом», «фиаско», от англ. «fuck up») — неудача/провал/облом (чаще имеют ввиду крупные/серьёзные ошибки', 'факап', 'fuck up');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (210, 'Фак  (или «ЧаВо», от англ. «FAQ») — блок ответов на часто задаваемые вопросы. Такой формат материала популярен на различных интернет-площадках и преследует цель заранее дать ответы на популярные вопросы пользователей', 'фак чаво', 'faq');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (211, 'Фидбек (от англ. «feedback») — 1) обратная связь, отзыв, рецензия о чем-либо; 2) в коммерческой сфере: любое упоминания от покупателя/пользователя в сети (отзыв, комментарий, сообщение)', 'фидбек', 'feedback');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (212, 'Фича (от англ. «feature») — уникальная особенность/свойство/функция какого либо объекта (ПО, приложения, ОС)', 'фича', 'feature');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (213, 'Флейм (или «флэйм», «флэйминг», от англ. «flame») — "спор ради спора", дискуссия, в ходе которой давно утеряна изначальная суть, продолжается в грубой форме с переходом на личности', 'флейм', 'flame');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (214, 'Флуд (от англ. «flood») — засорение чатов или других каналов связи различной информацией, не имеющей отношения к тематике канала (мемы, картинки, текст, обилие сообщений) (от англ. «flood») — засорение чатов или других каналов связи различной информацией, не имеющей отношения к тематике канала (мемы, картинки, текст, обилие сообщений)', 'флуд', 'flood');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (215, 'Форвард (или «форварднуть», «отфорвардить», от англ. «forward») — Форвард (форварднуть, отфорвардить, от forward) – переслать поступившее письмо другому пользователю', 'форвард', 'forward');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (216, 'Фреймворк (от англ. «framework») — специальная платформа/ПО, главной задачей которой является облегчение создания, поддержки и объединения разнообразных компонентов проекта/приложения/сервиса и т.д.', 'фреймворк', 'framework');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (217, 'Фриланс (от англ. «freelance») — оплачиваемая работа на дому (вне официального штата сотрудников ) Часто фрилансер работает на себя и не имеет постоянных заказчиков и начальства', 'фриланс', 'freelance');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (218, 'Фронтенд (от англ. «front-end») — создание «внешней оболочки» веб-сайта/приложения (то, что видит пользователь)', 'фронтенд', 'front-end');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (219, 'Фуллстек-разработчик (от англ. «full stack») — разработчик, который одновременно трудится в бэкендее и фронтэнде', 'фуллстек-разработчик', 'full stack');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (220, 'Хаб  (от англ. «hub») — 1) узел какой-либо сети; 2) сетевой концентратор (распространяет трафик от одного подключённого устройства ко всем остальным); 3) крупный раздающий узел сети', 'хаб', 'hub');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (221, 'Хакатон (от англ. «hack marathon») — мероприятие, где встречаются специалисты из разных отраслей разработки ПО (программисты, дизайнеры, тестеры и т.д.) для работы над общим проектом: приложением, программой', 'хакатон', 'hack marathon');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (222, 'Хардкодить (от англ. «hardcore») — привычка статически прописывать в коде данные, которые по правилам должны вычисляться динамически. Практика считается плохой, антипаттерн в программировании', 'хардкодить хардкод', 'hardcore');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (224, 'Хидден  (от англ. «hidden») — 1) то, что существует, но сокрыто от посторонних взглядов (к примеру, некоторые элементы интерфейса); 2) в Фидонете: невидимая/скрытая служебная строчка в письме; 3) логический HTML-атрибут, который скрывает элементы, которым назначен', 'хидден', 'hidden');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (225, 'Хинт (от англ. «hint») — 1) в общем смысле: совет/рекомендация/подсказка; 2) в графическом дизайне: элемент интерфейса, представляющий собой всплывающий текст-подсказку для обучения юзера', 'хинт', 'hint');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (226, 'Холивар (или «холивор», от англ. «holy war») — дословно "святая война", агрессивный спор между представителями противоположных мнений в интернете', 'холивар', 'holy war');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (227, 'Хостинг — услуга, позволяющая разместить свой сайт на выделенном или виртуальном сервере', 'хостинг', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (228, 'Хоткей (от англ. «hotkey») — горячая клавиша (или сочетание клавиш для быстрого доступа к необходимым командам', 'хоткей', 'hotkey');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (229, 'Хотфикс (от англ. «hot fix») — исправление обнаруженных ошибок (багов), требующее немедленного решения/с горящими сроками', 'хотфикс', 'hot fix');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (230, 'Хэдер (или «хедер», от англ. «header») — 1) элемент веб-страницы, расположенный в верхней его части и содержащий: логотип, меню, служебную информацию и т.д. 2) заголовочный файл библиотеки', 'хэдер', 'header');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (231, 'ЦОД (или «центр обработки данных», «дата-центр», от англ. «data center») — место расположения (хостинга) серверов/ИТ-инфраструктуры с целью обеспечения их бесперебойного функционирования', 'цод', 'data center');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (232, 'ЦП (или «проц», «цпу», «процик», «CPU», от англ. «central processing unit») — компьютерный компонент, обрабатывающий машинный код. Отвечает за интерпретацию и выполнение большинства команд от другого аппаратного и программного обеспечения компьютера', 'цп проц', 'cpu');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (233, 'Цэмээс (или «цээмэс», от англ. «CMS») — система управления контентом, которая используется для обеспечения и организации совместной работы над его созданием, редактированием и управлением', 'цэмээс цмс', 'cms');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (234, 'Чат  (от англ. «chat») — способ общения пользователей сети в режиме реального времени, по средствам обмена текстовыми сообщениями', 'чат', 'chat');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (235, 'Чекать  (от англ. «check») — что-то проверять, просматривать на предмет необходимой информации или для поиска ошибок', 'чекать', 'check');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (236, 'Чекбокс  (или «флажок», «флаговая кнопка», «галка», от англ. «check box») — элемент графического интерфейса, который дает пользователю возможность управлять параметром с двумя состояниями (например, ☑ включено и ☐ отключено)', 'чекбокс', 'check box');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (237, 'Чекиниться (или «зачекиниться», от англ. «check-in») — поставить отметку, подтверждающую ваше присутствие в каком-то определенном месте/мероприятии', 'чекиниться', 'check-in');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (238, 'Челлендж (от англ. «challenge») — 1) необычная нестандартная проблема/задача, решение которой можно считать своим достижением; 2) в социальных сетях: некая последовательность действий/слов, которую повторяет большое количество пользователей', 'челлендж', 'challenge');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (239, 'Черрипик (от англ. «cherry picking») — Команда git cherry-pick применяется для перенесения некоторых коммитов из одного места репозитория в другое', 'черрипик', 'cherry picking');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (240, 'Читерство (от англ. «cheating») — в компьютерных играх: процесс приобретения обманным путем каких-либо привилегий путем использования чит-кодов и специального ПО', 'читерство', 'cheating');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (241, 'ЧПУ — расшифровывается как "человекопонятный url". Это адрес страницы, отображаемый в адресной строке, состоящий из понятных для пользователя символов, коротко отражающих содержание активной страницы', 'чпу', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (242, 'Шарить  — 1) хорошо понимать, отлично разбираться в чём-либо; 2) "шерить", т.е. давать дугим доступ к чему-то, обычно к определенным папкам, файлам, хранилищам', 'шарить', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (243, 'Шредер (от англ. «shredder») — 1) агрегат для утилизации использованной офисной бумаги; 2) ПО, предназначенное для полного удаления файлов с компьютера (избегая корзины)', 'шредер', 'shredder');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (244, 'Эксплойт (от англ. «exploit») — фрагмент кода или вредоносная программа кода, которая способна выполнять атаки на вычислительную систему через найденную уязвимость в другой программе', 'эксплойт', 'exploit');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (245, 'Эпикфэйл (от англ. «epic fail») — дословно переводится как "эпический провал". Фиаско, крах, серьезная неудача', 'эпикфэйл', 'epic fail');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (246, 'Юзабилити (от англ. «usability») — показатель удобства работы пользователя с тем или иным продуктом или объектом', 'юзабилити', 'usability');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (247, 'Юзать (от англ. «use») — использовать/применять/пользоваться (например: "дай мне поюзать твой самокат")', 'юзать', 'use');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (248, 'Юзер (от англ. «user») — активный пользователь компьютера или Сети, идет сразу после "чайника"', 'юзер', 'user');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (249, 'Юзерпик  (или «аватар», «аватарка», от англ. «user picture») — графическое обозначение пользователя в Интернете (картинка/фото/изображение)', 'юзерпик', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (250, 'Юникс (или «юних», «уних», от англ. «Unix») — семейство гибких, многозадачных и многопользовательских ОС, характеризующихся модульным дизайном, где каждая задача выполняется отдельной утилитой, взаимодействуя посредстом единой файловой системы', 'юникс', 'unix');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (251, 'Яблочник (или «яблофаг», от англ. «Apple») — активный пользователь устройств бренда Apple или ярый фанат компании Apple', 'яблочник', NULL);
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (252, 'Тестирование на проникновение (тесты на преодоление защиты, penetration testing, pentest, пентест) представляет собой имитацию действий злоумышленника с информационной системой (сетью, оборудованием и т.д.) с целью демонстрации уязвимостей и оценки эффективности применяемых мер по защите информации (технических, организационных и др.).', 'пентест', 'penetration testing pentest');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (255, 'Ubuntu — это разрабатываемая сообществом, основанная на ядре Linux операционная система, которая идеально подходит для использования на персональных компьютерах, ноутбуках и серверах.', 'убунту', 'ubuntu');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (256, 'Свободное и открытое программное обеспечение для создания и конфигурирования виртуальной среды разработки. Является обёрткой для программного обеспечения виртуализации, например VirtualBox, и средств управления конфигурациями.', 'вагрант', 'vagrant');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (257, 'Apache Hadoop («Хадуп») — это набор инструментов для построения системы работы с большими данными. Он предназначен для сбора, хранения и распределённой обработки сотен терабайт информации, которая поступает непрерывным потоком. Именно на его основе строят озёра данных — объёмные хранилища, в которых хранится неструктурированная информация для будущей аналитики.', 'хадуп', 'hadoop');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (258, 'ACID (от англ. atomicity, consistency, isolation, durability) — набор требований к транзакционной системе, обеспечивающий наиболее надёжную и предсказуемую её работу — атомарность, согласованность, изоляция, надёжность.', 'асид', 'acid');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (259, 'SOLID (сокр. от англ. single responsibility, open–closed, Liskov substitution, interface segregation и dependency inversion) в программировании — мнемонический акроним, введённый Майклом Фэзерсом (Michael Feathers) для первых пяти принципов, названных Робертом Мартином в начале 2000-х, которые означали 5 основных принципов объектно-ориентированного программирования и проектирования.', 'солид', 'solid');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (260, 'Big Data или большие данные — это структурированные или неструктурированные массивы данных большого объема. Их обрабатывают при помощи специальных автоматизированных инструментов, чтобы использовать для статистики, анализа, прогнозов и принятия решений.', 'биг дата', 'big data');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (262, 'СУБД - система управления базами данных', 'субд', '');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (264, 'Kibana – это инструмент для визуализации на основе браузера с открытым исходным кодом, который в основном используется для анализа большого объема журналов в виде линейного графика, гистограммы, круговых диаграмм, тепловых карт, карт регионов, координатных карт, датчиков, целей, временных шкал и т. Д. Визуализация делает это Легко предсказать или увидеть изменения в тенденциях ошибок или других значительных событий источника ввода. Kibana работает синхронно с Elasticsearch и Logstash, которые вместе образуют так называемый стек ELK .', 'кибана', 'kibana');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (265, 'CSRF (Cross-Site Request Forgery, рус. "Межсайтовая подделка запроса") - вид атаки, при которой вражеский сайт выдаёт себя за доверенного пользователя и отсылает на сайт нежелательные команды.', '', 'csrf');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (267, 'От англ. backlog (дословно — очередь работ) — еще не запланированный объем работы, который требуется выполнить команде. Каждая созданная задача вначале попадает в бэклог, а потом уже в спринт.', 'бэклог', 'backlog');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (268, 'Agile — подход к управлению проектами, который помогает быстрее создавать качественные продукты и правильно развивать их. Такой результат становится возможным благодаря гибкости рабочих процессов и эффективному взаимодействию всех заинтересованных лиц: клиентов, заказчиков и команды проекта.', 'эджайл', 'agile');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (270, 'Cross-Origin Resource Sharing (CORS) — механизм, использующий дополнительные HTTP -заголовки, чтобы дать возможность агенту пользователя получать разрешения на доступ к выбранным ресурсам с сервера на источнике (домене), отличном от того, что сайт использует в данный момент.', '', 'cors');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (271, 'От англ. sprint (дословно — бег на короткую дистанцию) — заданный отрезок времени, за который нужно выполнить запланированный объем работы, чтобы в конце этого отрезка был ожидаемый результат.', 'спринт', 'sprint');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (269, 'От англ. daily (дословно — ежедневно) — ежедневные короткие (от 5 до 30 минут) встречи команды с целью поделиться прогрессом по выполненным задачам за предыдущий день и озвучить план работ на текущий день. Также дейли могут называть стендапом (от daily standup), потому что обычно такие встречи происходят стоя — для большей эффективности.', 'дэйли дейли', 'daily');
INSERT INTO public.slang_translator (id, description, search_query_ru, search_query_en) VALUES (272, 'От англ. specification (дословно — спецификация) — документ с подробным описанием требований, условий и технических характеристик, как должен работать разрабатываемый функционал.', 'спека спецификация', 'specification');


--
-- TOC entry 3265 (class 0 OID 0)
-- Dependencies: 202
-- Name: not_found_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.not_found_id_seq', 54, true);


--
-- TOC entry 3266 (class 0 OID 0)
-- Dependencies: 200
-- Name: slang_translator_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.slang_translator_id_seq', 272, true);


--
-- TOC entry 3125 (class 2606 OID 72263)
-- Name: not_found not_found_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.not_found
    ADD CONSTRAINT not_found_pkey PRIMARY KEY (id);


--
-- TOC entry 3123 (class 2606 OID 59589)
-- Name: slang_translator slang_translator_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slang_translator
    ADD CONSTRAINT slang_translator_pkey PRIMARY KEY (id);


-- Completed on 2022-12-20 12:56:32 MSK

--
-- PostgreSQL database dump complete
--


